user:
  outputs:
    default:
      account: ARXSWCE-VS35570
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: GITHUB_STAGING
      password: SM^@5hrvRB8MhS
      retry_on_database_errors: true
      role: null
      schema: dbt_dmachel
      threads: 6
      type: snowflake
      user: DBT_USER
      warehouse: TRANSFORM_WH
  target: default
